zboxcore/sdk/downloadworker.go
zboxcore/sdk/repairworker.go
zboxcore/sdk/sdk.go
zboxcore/sdk/uploadworker.go

Adding data[] array to inProgress method for faster streaming

adding data[] for streaming purpose

---

zboxcore/fileref/fileref.go
zboxcore/sdk/listworker.go

This PR adding actual file size and actual number of blocks for File (excluding thumbnail)

added actual file size and actual number of blocks for files

---

zboxcore/sdk/downloadworker.go

This commit fixed the bug with wrong chunks downloading.

Fixed bug with wrong chunks downloading

---

zboxcore/sdk/allocation.go

added numBlocks && actualSize to FileMeta request

added numBlocks && actualSize to FileMeta request

---

.github/workflows/unit-test.yml

Add GitHub action to run unit tests

Add GitHub action to run unit tests

---

zboxcore/zboxutil/http.go

Need to be merged with: 
https://github.com/0chain/blobber/pull/66

[WIP] Implement signature headers

---

zboxcore/sdk/sdk.go

wrongly named cancelallocation

---

core/version/version.go

Update version.go v1.2.6

---

.github/workflows/GitVersion.yml
.github/workflows/build.yml
GitVersion.yml
build.yml

Created github action file for making builds. Creating zip file along with source code to release with enabling latest build option.

Gitactionsfix

---

zboxcore/sdk/filemetaworker_test.go

Add test cases for filemetaworker.go

add filemetaworker.go test cases

---

core/zcncrypto/bls0chain.go
core/zcncrypto/bls0chain_test.go

function to convert MIRACL public keys to herumi/bls public keys

---

.github/workflows/ci.yml
core/clients/blobberClient/client.go
core/clients/blobberClient/client_helper_integration_test.go
core/clients/blobberClient/client_integration_test.go
go.mod
go.sum
zboxcore/sdk/commitworker.go

Integrating grpc version of "/v1/connection/commit/{allocation}"

---

zboxcore/sdk/sdk.go

Adds diverse bobbers request to create allocation request.
Works with https://github.com/0chain/blobber/pull/104 and https://github.com/0chain/0chain/pull/315.

Diversify blobbers

---

core/clients/blobberClient/client.go
core/clients/blobberClient/client_integration_test.go
zboxcore/sdk/collaboratorworker.go

Integrating CollaboratorHandler gRPC

---

core/clients/blobberClient/client.go
core/clients/blobberClient/client_integration_test.go
zboxcore/sdk/commitworker.go

Integrating CalculateHashHandler gRPC

---

core/clients/blobberClient/client.go
core/clients/blobberClient/client_integration_test.go
zboxcore/sdk/commitmetaworker.go

Integrating CommitMetaTxnHandler gRPC

---

core/transaction/entity.go
zboxcore/sdk/allocation.go
zboxcore/sdk/sdk.go

Issue https://github.com/0chain/gosdk/issues/120, need to access new endpoints in https://github.com/0chain/0chain/pull/366

Access to new curator endponts

---

core/transaction/entity.go
zboxcore/sdk/sdk.go

Part of issue https://github.com/0chain/0chain/issues/346. To be paired with 0chain PR https://github.com/0chain/0chain/pull/358 and zboxcli PR https://github.com/0chain/zboxcli/pull/44.
Wraps new endpoints.

Free allocation

---

core/util/httpnet.go
zboxcore/sdk/allocation_test.go
zboxcore/sdk/testdata/alloc/1.txt

update test cases for allocation.go

---

.github/workflows/ci.yml
Makefile
core/clients/blobberClient/client.go
core/clients/blobberClient/client_integration_test.go
go.mod
go.sum
zboxcore/sdk/attributesworker.go
zboxcore/sdk/collaboratorworker.go
zboxcore/sdk/commitmetaworker.go
zboxcore/sdk/commitworker.go
zboxcore/sdk/common.go
zboxcore/sdk/copyworker.go
zboxcore/sdk/deleteworker.go
zboxcore/sdk/filemetaworker.go
zboxcore/sdk/filestatsworker.go
zboxcore/sdk/listworker.go
zboxcore/sdk/renameworker.go

feat: updgrade the grpc client to utilise upgraded stubs

---

go.mod
go.sum

Fix wasm build for go-ethereum package

---

zboxcore/sdk/dirworker.go

This change resolves wrongly set ID in looper

[BUG] resolving wrong id's

---

core/zcncrypto/bls0chain.go
core/zcncrypto/ed255190chain.go
zcncore/mswallet.go

Use IETF RFC3339 date format when creating wallets

---

go.mod
go.sum
zboxcore/zboxutil/util.go

fix(zboxutil):update NewConnectionId with google/uuid

---

go.mod
go.sum

fix(zboxutil):#178 go mod tidy

---

zboxcore/sdk/sdk.go

Allows direct viewing of MPT key.

Wraps 0chain getMptKey endpoint

---

core/transaction/entity.go
zboxcore/sdk/sdk.go

Works with https://github.com/0chain/0chain/pull/470 needed for https://github.com/0chain/zboxcli/pull/83

Wrap 0chain remove-curator endpoint

---

core/clients/blobberClient/client.go
zboxcore/sdk/filestatsworker.go

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

feat: add logs in the conversion logic

---

core/transaction/entity.go
zcncore/transaction.go
zcncore/transactionauth.go

Wraps the 0chain delete_miner and delete_sharder. endpoints.
Requires 0chian https://github.com/0chain/0chain/pull/481 and needed for https://github.com/0chain/zwalletcli/pull/35

Wrap delete_miner and delete_sharder.

---

core/transaction/entity.go
zcncore/transaction.go
zcncore/transactionauth.go

Revert "Wrap delete_miner and delete_sharder."

---

.github/workflows/unit-test.yml

Give Pr checks to staging branch.

Add staging to PR check

---

core/transaction/entity.go
zboxcore/sdk/sdk.go

This PR fixes the issue https://github.com/0chain/zboxcli/issues/53 once the PR https://github.com/0chain/0chain/pull/523 is merged to 0chain core repo.

handle failed sc txns by treating them as error

---

core/transaction/entity.go
zcncore/wallet.go

Matched with 0chain https://github.com/0chain/0chain/pull/524

Update globals changes to endpoint names

---

core/zcncrypto/bls0chain.go
core/zcncrypto/bls0chain_test.go
go.mod
go.sum

see detail on https://0chain.slack.com/archives/G01GMABG2T1/p1631608351009600

fix(zcncrypto):reverted bls to bls-go-binary
